// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: rpc/route/route.proto

package route

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cpu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brand         string  `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Name          string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NumberCores   string  `protobuf:"bytes,3,opt,name=number_cores,json=numberCores,proto3" json:"number_cores,omitempty"`
	NumberThreads string  `protobuf:"bytes,4,opt,name=number_threads,json=numberThreads,proto3" json:"number_threads,omitempty"`
	MinGhz        float64 `protobuf:"fixed64,5,opt,name=min_ghz,json=minGhz,proto3" json:"min_ghz,omitempty"`
	MaxGhz        float64 `protobuf:"fixed64,6,opt,name=max_ghz,json=maxGhz,proto3" json:"max_ghz,omitempty"`
}

func (x *Cpu) Reset() {
	*x = Cpu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_route_route_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cpu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cpu) ProtoMessage() {}

func (x *Cpu) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_route_route_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cpu.ProtoReflect.Descriptor instead.
func (*Cpu) Descriptor() ([]byte, []int) {
	return file_rpc_route_route_proto_rawDescGZIP(), []int{0}
}

func (x *Cpu) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Cpu) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cpu) GetNumberCores() string {
	if x != nil {
		return x.NumberCores
	}
	return ""
}

func (x *Cpu) GetNumberThreads() string {
	if x != nil {
		return x.NumberThreads
	}
	return ""
}

func (x *Cpu) GetMinGhz() float64 {
	if x != nil {
		return x.MinGhz
	}
	return 0
}

func (x *Cpu) GetMaxGhz() float64 {
	if x != nil {
		return x.MaxGhz
	}
	return 0
}

type CpuOfBrandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brand string `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
}

func (x *CpuOfBrandRequest) Reset() {
	*x = CpuOfBrandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_route_route_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpuOfBrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuOfBrandRequest) ProtoMessage() {}

func (x *CpuOfBrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_route_route_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuOfBrandRequest.ProtoReflect.Descriptor instead.
func (*CpuOfBrandRequest) Descriptor() ([]byte, []int) {
	return file_rpc_route_route_proto_rawDescGZIP(), []int{1}
}

func (x *CpuOfBrandRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

type CpuOfNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CpuOfNameRequest) Reset() {
	*x = CpuOfNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_route_route_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpuOfNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuOfNameRequest) ProtoMessage() {}

func (x *CpuOfNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_route_route_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuOfNameRequest.ProtoReflect.Descriptor instead.
func (*CpuOfNameRequest) Descriptor() ([]byte, []int) {
	return file_rpc_route_route_proto_rawDescGZIP(), []int{2}
}

func (x *CpuOfNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CpuNumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *CpuNumberResponse) Reset() {
	*x = CpuNumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_route_route_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpuNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuNumberResponse) ProtoMessage() {}

func (x *CpuNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_route_route_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuNumberResponse.ProtoReflect.Descriptor instead.
func (*CpuNumberResponse) Descriptor() ([]byte, []int) {
	return file_rpc_route_route_proto_rawDescGZIP(), []int{3}
}

func (x *CpuNumberResponse) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_rpc_route_route_proto protoreflect.FileDescriptor

var file_rpc_route_route_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2f, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x22, 0xab,
	0x01, 0x0a, 0x03, 0x43, 0x70, 0x75, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x43, 0x6f,
	0x72, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x74, 0x68,
	0x72, 0x65, 0x61, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x69,
	0x6e, 0x5f, 0x67, 0x68, 0x7a, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x6d, 0x69, 0x6e,
	0x47, 0x68, 0x7a, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x5f, 0x67, 0x68, 0x7a, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x47, 0x68, 0x7a, 0x22, 0x29, 0x0a, 0x11,
	0x43, 0x70, 0x75, 0x4f, 0x66, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x22, 0x26, 0x0a, 0x10, 0x43, 0x70, 0x75, 0x4f, 0x66,
	0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x2b, 0x0a, 0x11, 0x43, 0x70, 0x75, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0xfb, 0x01, 0x0a,
	0x0a, 0x43, 0x70, 0x75, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x50, 0x55, 0x12, 0x17, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x2e, 0x43, 0x70, 0x75, 0x4f, 0x66, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0a, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x43, 0x70, 0x75, 0x12, 0x3b, 0x0a,
	0x11, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x50, 0x55, 0x4f, 0x66, 0x4f, 0x6e, 0x65, 0x42, 0x72, 0x61,
	0x6e, 0x64, 0x12, 0x18, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x43, 0x70, 0x75, 0x4f, 0x66,
	0x42, 0x72, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x2e, 0x43, 0x70, 0x75, 0x30, 0x01, 0x12, 0x43, 0x0a, 0x0b, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x2e, 0x43, 0x70, 0x75, 0x4f, 0x66, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x43, 0x70, 0x75, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12,
	0x39, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x50, 0x55, 0x4f, 0x66, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x12, 0x17, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x43, 0x70, 0x75, 0x4f, 0x66, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x2e, 0x43, 0x70, 0x75, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x69, 0x69, 0x63, 0x61, 0x72, 0x75,
	0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x2f, 0x72, 0x70, 0x63, 0x2f,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x3b, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_rpc_route_route_proto_rawDescOnce sync.Once
	file_rpc_route_route_proto_rawDescData = file_rpc_route_route_proto_rawDesc
)

func file_rpc_route_route_proto_rawDescGZIP() []byte {
	file_rpc_route_route_proto_rawDescOnce.Do(func() {
		file_rpc_route_route_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_route_route_proto_rawDescData)
	})
	return file_rpc_route_route_proto_rawDescData
}

var file_rpc_route_route_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_route_route_proto_goTypes = []interface{}{
	(*Cpu)(nil),               // 0: route.Cpu
	(*CpuOfBrandRequest)(nil), // 1: route.CpuOfBrandRequest
	(*CpuOfNameRequest)(nil),  // 2: route.CpuOfNameRequest
	(*CpuNumberResponse)(nil), // 3: route.CpuNumberResponse
}
var file_rpc_route_route_proto_depIdxs = []int32{
	2, // 0: route.CpuService.SearchCPU:input_type -> route.CpuOfNameRequest
	1, // 1: route.CpuService.ListCPUOfOneBrand:input_type -> route.CpuOfBrandRequest
	1, // 2: route.CpuService.CountNumber:input_type -> route.CpuOfBrandRequest
	2, // 3: route.CpuService.ListCPUOfNames:input_type -> route.CpuOfNameRequest
	0, // 4: route.CpuService.SearchCPU:output_type -> route.Cpu
	0, // 5: route.CpuService.ListCPUOfOneBrand:output_type -> route.Cpu
	3, // 6: route.CpuService.CountNumber:output_type -> route.CpuNumberResponse
	0, // 7: route.CpuService.ListCPUOfNames:output_type -> route.Cpu
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_route_route_proto_init() }
func file_rpc_route_route_proto_init() {
	if File_rpc_route_route_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_route_route_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cpu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_route_route_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpuOfBrandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_route_route_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpuOfNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_route_route_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpuNumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_route_route_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_route_route_proto_goTypes,
		DependencyIndexes: file_rpc_route_route_proto_depIdxs,
		MessageInfos:      file_rpc_route_route_proto_msgTypes,
	}.Build()
	File_rpc_route_route_proto = out.File
	file_rpc_route_route_proto_rawDesc = nil
	file_rpc_route_route_proto_goTypes = nil
	file_rpc_route_route_proto_depIdxs = nil
}
